# TensorFlow Intro

In [1]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/5a/f2/5c2f878c62c8b79c629b11b33516bb55054d7677eba6f56f3a20296b56bd/tensorflow-2.13.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached tensorflow-2.13.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Using cached tensorflow-2.13.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
Note: you may need to restart the kernel to use updated packages.


In [ ]:
# To run nightly build
# pip install tf-nightly

In [ ]:
# To run via docker
# docker pull tensorflow/tensorflow:latest  # Download latest stable image
# docker run -it -p 8888:8888 tensorflow/tensorflow:latest-jupyter  # Start Jupyter server 

In [7]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2023-08-19 16:16:32.559973: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-19 16:16:32.599928: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-19 16:16:32.600669: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-19 16:16:33.591966: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


TensorFlow version: 2.13.0


In [6]:
from IPython.display import display_html
def restartkernel() :
    display_html("<script>Jupyter.notebook.kernel.restart()</script>",raw=True)
restartkernel()

In [8]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 2s 0us/step


In [9]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2023-08-19 16:18:49.283962: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: UNKNOWN ERROR (100)


In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.846338  , -0.11360441,  0.00889862,  0.640205  ,  0.36351833,
        -0.39257765, -0.00474551, -0.23367387,  0.15858623, -0.6022401 ]],
      dtype=float32)

In [11]:
tf.nn.softmax(predictions).numpy()

array([[0.19839896, 0.07596993, 0.08587053, 0.16144218, 0.12242032,
        0.05747582, 0.08470684, 0.0673746 , 0.09973615, 0.04660472]],
      dtype=float32)

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2903 - accuracy: 0.9146
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1391 - accuracy: 0.9583
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1036 - accuracy: 0.9688
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0874 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0718 - accuracy: 0.9776


In [15]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0787 - accuracy: 0.9762 - 573ms/epoch - 2ms/step


[0.07873629033565521, 0.9761999845504761]

In [16]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.3835490e-07, 1.7806895e-09, 5.2183054e-06, 3.4641758e-05,
        1.6390233e-11, 1.0995037e-06, 7.9904031e-15, 9.9995220e-01,
        7.5843175e-08, 6.3110142e-06],
       [1.1226172e-08, 9.4751107e-05, 9.9982589e-01, 5.9130649e-05,
        7.3664910e-16, 9.6050981e-06, 2.6249276e-07, 2.9125872e-11,
        1.0384181e-05, 5.2129403e-14],
       [3.0326505e-06, 9.9857640e-01, 1.6762908e-04, 2.4313609e-05,
        2.2657350e-05, 5.4811344e-06, 5.9908692e-04, 5.2218849e-04,
        7.7906006e-05, 1.2754092e-06],
       [9.9989760e-01, 1.6023536e-09, 5.1837702e-05, 1.1245842e-07,
        7.1824633e-07, 1.8637971e-05, 8.4869698e-06, 2.7137605e-06,
        7.7959544e-07, 1.9091023e-05],
       [5.0283807e-06, 1.7376439e-10, 1.3059710e-06, 8.9677582e-10,
        9.9706429e-01, 9.6027281e-07, 1.6594551e-05, 1.8942988e-05,
        6.4099403e-08, 2.8928223e-03]], dtype=float32)>